version: '1.0'
services: 
  paperlessui:
    image: if20b113/paperlessui
    ports:
      - 4200:4200 

  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    ports:
      - 5432:5432
volumes:
  pgdata: